"""Generate frontend DTOs from the assembled OpenAPI and WebSocket contracts.

Run from backend: python scripts/generate_frontend_types.py [--check]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

ALIASES = {
    'ValidationIssue': 'ValidationIssueOut',
    'ExtensionRecord': 'ExtensionOut',
    'CatalogComponent': 'ComponentOut',
    'CatalogTool': 'ToolOut',
    'PromptProfile': 'PromptProfileOut',
    'RuntimeConfig': 'RuntimeConfigOut',
    'RuntimeConfigValidation': 'RuntimeConfigValidationOut',
    'EvalLeaderboardItem': 'LeaderboardItem',
    'EvalLeaderboardResponse': 'LeaderboardResponse',
    'EvalAccountCheckpointItem': 'AccountCheckpointItem',
    'EvalAccountCheckpointsResponse': 'AccountCheckpointsResponse',
    'MarketBar': 'KlineItem',
}
OUTPUT = Path(__file__).resolve().parents[2] / 'frontend/app/lib/api/generated-types.ts'


def identifier(name):
    return re.sub(r'[^a-zA-Z0-9_]', '_', name)


def ts_type(schema):
    if '$ref' in schema:
        return identifier(schema['$ref'].rsplit('/', 1)[-1])
    if 'const' in schema:
        return json.dumps(schema['const'], ensure_ascii=False)
    if 'enum' in schema:
        return ' | '.join(json.dumps(value, ensure_ascii=False) for value in schema['enum'])
    for key in ('anyOf', 'oneOf', 'allOf'):
        if key in schema:
            joiner = ' & ' if key == 'allOf' else ' | '
            return '(' + joiner.join(ts_type(item) for item in schema[key]) + ')'
    kind = schema.get('type')
    if isinstance(kind, list):
        return '(' + ' | '.join(ts_type({**schema, 'type': value}) for value in kind) + ')'
    if kind in ('number', 'integer'):
        return 'number'
    if kind in ('string', 'boolean', 'null'):
        return kind
    if kind == 'array':
        return 'Array<' + ts_type(schema.get('items', {})) + '>'
    if kind == 'object' or 'properties' in schema:
        properties = schema.get('properties', {})
        required = schema.get('required', [])
        fields = [f'{json.dumps(name)}{"" if name in required else "?"}: {ts_type(value)}' for name, value in properties.items()]
        additional = schema.get('additionalProperties')
        if isinstance(additional, dict):
            fields.append('[key: string]: ' + ts_type(additional))
        elif additional is True or not properties and additional is not False:
            fields.append('[key: string]: unknown')
        return '{ ' + '; '.join(fields) + ' }'
    return 'unknown'


def contracts():
    from benchmark.bootstrap.app import create_app
    from benchmark.bootstrap.runtime import StartupMode
    return create_app(mode=StartupMode.NO_BACKGROUND).openapi()['components']['schemas']


def render(schemas):
    lines = ['// Generated by backend/scripts/generate_frontend_types.py. Do not edit.']
    for name, schema in sorted(schemas.items()):
        lines.append(f'export type {identifier(name)} = {ts_type(schema)}')
    for name, target in sorted(ALIASES.items()):
        if target + '-Output' in schemas:
            target += '-Output'
        if target not in schemas:
            raise ValueError(f'Missing OpenAPI schema: {target}')
        lines.append(f'export type {name} = {identifier(target)}')
    for name in ('RuntimeConfigBody',):
        if name + '-Output' in schemas:
            lines.append(f'export type {name} = {identifier(name + "-Output")}')
    return '\n\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render(contracts())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit('Frontend DTO drift: run python scripts/generate_frontend_types.py')
    else:
        OUTPUT.write_text(expected)


if __name__ == '__main__':
    main()
