// Generated by backend/scripts/generate_frontend_types.py. Do not edit.

export type AIDecision = { "id": number; "decision_time": string; "operation": string; "symbol": (string | null); "prev_portion": number; "target_portion": number; "total_balance": number; "leverage": (number | null); "executed": string; "reason": (string | null); "order_id": (number | null) }

export type AccountCheckpointItem = { "period_start"?: (string | null); "period_end"?: (string | null); "equity_start"?: (number | null); "equity_end"?: (number | null); "pnl"?: (number | null); "return_rate": number; "volatility"?: (number | null); "created_at"?: (string | null) }

export type AccountCheckpointsResponse = { "account_id": number; "account_name": string; "interval_seconds": number; "items": Array<AccountCheckpointItem> }

export type AccountSystemPromptResponse = { "account_id": number; "account_name": string; "agent_type": string; "agent_id": string; "memory_enabled": boolean; "tool_routing_enabled": boolean; "decision_protocol": string; "termination_token": string; "system_prompt": string; "prompt_profile_id": (string | null); "prompt_profile_version": (string | null); "prompt_id": (string | null); "prompt_version": (string | null); "prompt_hash": (string | null) }

export type AgentStep = { "step_number": number; "role": string; "content": (string | null); "tool_calls": unknown; "tool_output": unknown; "created_at": (string | null) }

export type AgentTrace = { "trace_id": string; "steps": Array<AgentStep>; "events": Array<RuntimeEvent>; "schema_version": number }

export type AssetCurvePoint = { "timestamp": number; "datetime_str": string; "total_assets": number; "initial_capital": number; "profit": number; "user_id": number; "username": string }

export type CompareItem = { "account_id": number; "agent_name"?: (string | null); "period_start"?: (string | null); "period_end"?: (string | null); "pnl"?: (number | null); "return_rate": number; "volatility"?: (number | null) }

export type CompareResponse = { "interval_seconds": number; "items"?: Array<CompareItem> }

export type ComplianceAggregate = { "gate_pass_rate": number; "avg_final_score": (number | null); "avg_s_rule_sat": (number | null); "avg_s_audit": (number | null); "evaluation_count": number }

export type ComplianceHistory = { "total": number; "limit": number; "offset": number; "records": Array<ComplianceRecord> }

export type ComplianceRecord = { "id": number; "timestamp": (string | null); "trace_id": (string | null); "gate_pass": boolean; "s_rule_sat": (number | null); "s_audit": (number | null); "final_score": (number | null) }

export type ComplianceResultDTO = { "account_id": (number | null); "account_name": (string | null); "trace_id": (string | null); "decision_round_id": (string | null); "component_versions": { [key: string]: (string | null) }; "gate_pass": (boolean | null); "s_rule_sat": (number | null); "s_audit": (number | null); "final_score": (number | null) }

export type ComplianceStats = { "total_evaluations": number; "all_time": (ComplianceAggregate | null); "recent_7d": (ComplianceAggregate | null); "llm_audit_stats": (LLMAuditStats | null) }

export type ComplianceTrend = { "period": string; "metric": string; "data_points": Array<TrendDataPoint> }

export type ComponentOut = { "id": string; "name": string; "version": string; "description": string; "source": string; "status": string; "config_schema": { [key: string]: unknown }; "requested_capabilities": Array<string>; "allowed_capabilities": Array<string> }

export type ComponentSchemaOut = { "component_id": string; "component_type": string; "version": string; "schema": { [key: string]: unknown } }

export type DecisionCompliance = { "gate_pass": (boolean | null); "final_score": (number | null); "s_audit": (number | null) }

export type DecisionSchedule = { "job_id": string; "interval_seconds": string; "first_execution_time": string; "next_decision_time_utc": string; "next_decision_time_utc8": string }

export type ExtensionOut = { "id": (string | null); "version": (string | null); "name": (string | null); "description": string; "source": string; "status": string; "requested_capabilities": Array<string>; "allowed_capabilities": Array<string>; "errors": Array<ValidationIssueOut> }

export type HTTPValidationError = { "detail"?: Array<ValidationError> }

export type KlineItem = { "timestamp": number; "datetime": string; "open": (number | null); "high": (number | null); "low": (number | null); "close": (number | null); "volume": (number | null); "amount": (number | null); "chg": (number | null); "percent": (number | null) }

export type KlineResponse = { "symbol": string; "market": string; "period": string; "count": number; "data": Array<KlineItem> }

export type LLMAuditStats = { "count": number; "avg_score": (number | null); "avg_coverage": (number | null); "avg_conflict": (number | null) }

export type LeaderboardItem = { "account_id": number; "agent_name"?: (string | null); "agent_type"?: (string | null); "equity_start"?: (number | null); "equity_end"?: (number | null); "pnl"?: (number | null); "return_rate": number; "volatility"?: (number | null) }

export type LeaderboardResponse = { "interval_seconds": number; "period_end"?: (string | null); "order_by"?: (string | null); "items"?: Array<LeaderboardItem> }

export type ManualDecisionRequest = { "account_ids": Array<number>; "max_concurrency"?: number }

export type MarketStatusResponse = { "symbol": string; "market"?: string; "market_status": string; "timestamp": number; "current_time": string }

export type OrderCancelResult = { "message": string; "order_id": number }

export type OrderCreateRequest = { "user_id": number; "symbol": string; "name": string; "market"?: string; "side": string; "order_type": string; "price"?: (number | null); "quantity": number; "leverage"?: number; "username"?: (string | null); "password"?: (string | null); "session_token"?: (string | null) }

export type OrderExecutionResult = { "order_id": number; "executed": boolean; "message": string }

export type OrderHealthResult = { "status": string; "timestamp": number; "statistics": { [key: string]: number }; "message": string }

export type OrderOut = { "id": number; "order_no": string; "user_id": number; "symbol": string; "name": string; "market": string; "side": string; "order_type": string; "price": (number | null); "quantity": number; "leverage": number; "filled_quantity": number; "status": string }

export type OrderProcessingResult = { "executed_count": number; "total_checked": number; "message": string }

export type PortfolioAccount = { "id": number; "user_id": number; "name": string; "account_type": string; "initial_capital": number; "current_cash": number; "frozen_cash": number; "enable_rule_aware"?: (boolean | null) }

export type PortfolioOrder = { "id": number; "order_no": string; "user_id": number; "symbol": string; "name": string; "market": string; "side": string; "order_type": string; "price": (number | null); "quantity": number; "leverage": number; "filled_quantity": number; "status": string }

export type PortfolioOverview = { "account": PortfolioAccount; "return_rate": number; "total_notional_value": number; "positions_notional_value": number; "total_assets": number; "positions_market_value": number }

export type PortfolioPosition = { "id": number; "account_id"?: (number | null); "user_id"?: (number | null); "symbol": string; "name": string; "market": string; "quantity": number; "available_quantity": number; "side"?: (string | null); "avg_cost": number; "leverage": number; "last_price": (number | null); "market_value": (number | null); "notional_value": (number | null) }

export type PortfolioSnapshot = { "type": string; "overview": PortfolioOverview; "positions": Array<PortfolioPosition>; "orders": Array<PortfolioOrder>; "trades": Array<PortfolioTrade>; "ai_decisions": Array<AIDecision>; "all_asset_curves"?: (Array<AssetCurvePoint> | null); [key: string]: unknown }

export type PortfolioTrade = { "id": number; "order_id": number; "user_id": number; "symbol": string; "name": string; "market": string; "side": string; "price": number; "quantity": number; "commission": number; "trade_time": string }

export type PortfolioUser = { "id": number; "username": string }

export type PriceResponse = { "symbol": string; "market": string; "price": number; "timestamp": number }

export type PromptProfileOut = { "id": string; "name": string; "version": string; "description": string; "source": string; "status": string; "slots": { [key: string]: { [key: string]: (string | null) } }; "requested_capabilities": Array<string>; "allowed_capabilities": Array<string> }

export type RecentDecision = { "trace_id": (string | null); "timestamp": (string | null); "operation": string; "symbol": (string | null); "leverage": (number | null); "executed": boolean; "compliance": (DecisionCompliance | null) }

export type RecentDecisions = { "account_id": number; "count": number; "decisions": Array<RecentDecision> }

export type RequiredConfigStatus = { "has_required_configs": boolean; "missing_configs"?: Array<string> }

export type RuleCategories = { "r0": RuleCategory; "r1": RuleCategory; "r2": RuleCategory }

export type RuleCategory = { "name": string; "description": string; "count": number }

export type RuleItem = { "id": string; "name": string; "category": string; "category_name": string; "weight"?: number }

export type RuleList = { "total": number; "rules": Array<RuleItem> }

export type RuleSummary = { "total_rules": number; "r0_count": number; "r1_count": number; "r2_count": number; "categories": RuleCategories }

export type RuntimeConfigBody_Input = { "agent_id": string; "agent_version"?: (string | null); "agent_config"?: { [key: string]: unknown }; "toolset_ids"?: Array<string>; "disabled_tools"?: Array<string>; "prompt_profile_id"?: (string | null); "prompt_profile_version"?: (string | null); "component_versions"?: { [key: string]: string } }

export type RuntimeConfigBody_Output = { "agent_id": string; "agent_version": (string | null); "agent_config": { [key: string]: unknown }; "toolset_ids": Array<string>; "disabled_tools": Array<string>; "prompt_profile_id": (string | null); "prompt_profile_version": (string | null); "component_versions": { [key: string]: string } }

export type RuntimeConfigOut = { "account_id": number; "config": RuntimeConfigBody_Output; "validation_status": string; "validation_errors": Array<ValidationIssueOut>; "updated_at": (string | null) }

export type RuntimeConfigSaveRequest = { "config": RuntimeConfigBody_Input; "expected_updated_at"?: (string | null) }

export type RuntimeConfigValidateRequest = { "config": RuntimeConfigBody_Input }

export type RuntimeConfigValidationOut = { "valid": boolean; "status": string; "config": (RuntimeConfigBody_Output | null); "errors": Array<ValidationIssueOut>; "warnings": Array<ValidationIssueOut> }

export type RuntimeEvent = { "id": string; "type": string; "account_id": number; "decision_round_id": string; "payload": { [key: string]: unknown }; "created_at": string }

export type ToolOut = { "id": string; "name": string; "version": string; "description": string; "source": string; "status": string; "side_effect": string; "requested_capabilities": Array<string>; "allowed_capabilities": Array<string> }

export type ToolsetOut = { "id": string; "name": string; "version": string; "description": string; "source": string; "status": string; "config_schema": { [key: string]: unknown }; "requested_capabilities": Array<string>; "allowed_capabilities": Array<string>; "tool_names": Array<string> }

export type TraceSummary = { "trace_id": string; "timestamp": string; "operation": string; "symbol": (string | null); "reason": string }

export type TradingAccount = { "id": number; "user_id": number; "username": string; "name": string; "account_type": string; "agent_type": (string | null); "memory_enabled": (string | null); "tool_routing_enabled": (string | null); "enable_rule_aware": boolean; "initial_capital": number; "current_cash": number; "frozen_cash": number; "model": (string | null); "base_url": (string | null); "api_key": (string | null); "is_active": boolean }

export type TradingAccountCreate = { "name": string; "model"?: (string | null); "base_url"?: (string | null); "api_key"?: (string | null); "agent_type"?: string; "memory_enabled"?: string; "tool_routing_enabled"?: string; "enable_rule_aware"?: boolean; "initial_capital"?: number; "account_type"?: string }

export type TradingAccountUpdate = { "name"?: (string | null); "model"?: (string | null); "base_url"?: (string | null); "api_key"?: (string | null); "agent_type"?: (string | null); "memory_enabled"?: (string | null); "tool_routing_enabled"?: (string | null); "enable_rule_aware"?: (boolean | null) }

export type TrendDataPoint = { "date": string; "value": number; "count": number }

export type ValidationError = { "loc": Array<(string | number)>; "msg": string; "type": string; "input"?: unknown; "ctx"?: { [key: string]: unknown } }

export type ValidationIssueOut = { "path": string; "message": string; "code": (string | null); "validator": (string | null) }

export type CatalogComponent = ComponentOut

export type CatalogTool = ToolOut

export type EvalAccountCheckpointItem = AccountCheckpointItem

export type EvalAccountCheckpointsResponse = AccountCheckpointsResponse

export type EvalLeaderboardItem = LeaderboardItem

export type EvalLeaderboardResponse = LeaderboardResponse

export type ExtensionRecord = ExtensionOut

export type MarketBar = KlineItem

export type PromptProfile = PromptProfileOut

export type RuntimeConfig = RuntimeConfigOut

export type RuntimeConfigValidation = RuntimeConfigValidationOut

export type ValidationIssue = ValidationIssueOut

export type RuntimeConfigBody = RuntimeConfigBody_Output
